apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-api
  namespace: app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - sample-api.demo.local
      secretName: sample-api-tls
  rules:
    - host: sample-api.demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sample-api
                port:
                  number: 80
